version: '3'
services: 
    web:
        build: .
        ports:
            - 3000:3000
        command: rails server -b 0.0.0.0
        environment: 
            - RAILS_ENV=production
            - RAILS_SERVE_STATIC_FILES=true
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example

